baseURL = "https://regazofotografia.com/"
title = "Regazo Fotografía"

languageCode = "es-es"
defaultContentLanguage = "es"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = false
canonifyURLs = true

copyright = "© Regazo Fotografía"
googleAnalytics = ""
pygmentsUseClasses = true
pygmentsCodeFences = true
disableKinds = ["taxonomy", "taxonomyTerm"]

# [taxonomies]
#   design = "designs"
#   tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[languages]
  [languages.es]
    languageName = "Spanish"
    languageCode = "es-es"
    weight = 1

[params]
  breadcrumb = true
  accentColor = "#dd88aa"
  mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404
  googleSiteVerification = ""
  author = "Regazo Fotografía"
  intro = "Bienvenid@ a <strong><a href=\"/\">Regazo Fotografía</a></strong>, fotografía documental de partos y familias en Cantabria"

  [params.ogimage]
    url = "/images/logo.png"
    width = 1024
    height = 1024

  [params.sidebar]
    backgroundImage = "/images/bg-dscf1990.jpg"
    logo = "/images/profile.JPG"

  [params.sections]
    # Define how your sections will be called
    # when automatically pulled. For instance in the 404 page
    post = "article"
    portfolio = "project"

  [params.social]
    # github = "https://github.com/"
    # twitter = "https://twitter.com/"
    # linkedin = "https://www.linkedin.com/in/"
    # medium = "https://medium.com/"
    # codepen = "https://codepen.io/"
    facebook = "https://www.facebook.com/regazofotografia"
    # youtube = "https://www.youtube.com/"
    instagram = "https://www.instagram.com/regazofotografia/"
    # gitlab = "https://gitlab.com/"
    # keybase = "https://keybase.io/"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false